// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCUgSZ6KTOHKdrDYGsOw_tglCM8ZkPFvk',
    appId: '1:203479776076:web:357155d4e72365db0e6de9',
    messagingSenderId: '203479776076',
    projectId: 'pc-hardware-parts-app',
    authDomain: 'pc-hardware-parts-app.firebaseapp.com',
    storageBucket: 'pc-hardware-parts-app.appspot.com',
    measurementId: 'G-V1Y50W9QQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW9VWKl0sGpzcwUnOu-qqTT0uLRCS1zNY',
    appId: '1:203479776076:android:21249987c19b2ff30e6de9',
    messagingSenderId: '203479776076',
    projectId: 'pc-hardware-parts-app',
    storageBucket: 'pc-hardware-parts-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1A0PTcx63BAKxwUh_f9i88J5uUzEGk24',
    appId: '1:203479776076:ios:c55960fdd078fb0b0e6de9',
    messagingSenderId: '203479776076',
    projectId: 'pc-hardware-parts-app',
    storageBucket: 'pc-hardware-parts-app.appspot.com',
    iosBundleId: 'com.example.pcHardwareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1A0PTcx63BAKxwUh_f9i88J5uUzEGk24',
    appId: '1:203479776076:ios:c55960fdd078fb0b0e6de9',
    messagingSenderId: '203479776076',
    projectId: 'pc-hardware-parts-app',
    storageBucket: 'pc-hardware-parts-app.appspot.com',
    iosBundleId: 'com.example.pcHardwareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCUgSZ6KTOHKdrDYGsOw_tglCM8ZkPFvk',
    appId: '1:203479776076:web:089ca32023e9aafc0e6de9',
    messagingSenderId: '203479776076',
    projectId: 'pc-hardware-parts-app',
    authDomain: 'pc-hardware-parts-app.firebaseapp.com',
    storageBucket: 'pc-hardware-parts-app.appspot.com',
    measurementId: 'G-G0G8EFP1MD',
  );
}
